version: 0.2
phases:
  install:
    commands:
      - python -V
      - pip install -r requirements.txt
  pre_build:
    commands:
      - pip show robotframework
      - rfbrowser init
      - playwright install chromium
      - npx playwright install-deps
  build:
    commands:
      - python -m robot -v from:aws -v env:beta tests/
      - export FOLDER=$(date +%Y-%m-%d_%H:%M)
      - mkdir $FOLDER
      - mv log.html $FOLDER
      - mv report.html $FOLDER/index.html
      - mv *.png $FOLDER
artifacts:
  files:
    - '**/*.html'
    - '**/*.png'
  name: log-report
