version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.4
    commands:
      - python -V
      - pip install -r requirements.txt
  build:
    commands:
      - apk add --no-cache tzdata
      - ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - echo "America/Sao_Paulo" > /etc/timezone
      - python -m robot -v from:aws -v env:beta tests/ || true
      - export FOLDER=$(date +%Y-%m-%d_%H:%M)
      - mkdir $FOLDER
      - mv log.html $FOLDER
      - mv report.html $FOLDER/index.html
      - mv *.png $FOLDER
artifacts:
  files:
    - '**/*.html'
    - '**/*.png'
  name: log-report
