version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python -m pip install --upgrade pip
      - pip install --cache-dir $HOME/.pip-cache -r requirements.txt
      - sudo apt-get update
      - sudo apt-get install -y xvfb

  pre_build:
    commands:
      - pip show robotframework
      - rfbrowser init

  build:
    commands:
      - xvfb-run -a python -m robot -v from:aws -v env:beta tests/
      - export FOLDER=$(date +%Y-%m-%d_%H:%M)
      - mkdir $FOLDER
      - mv log.html $FOLDER
      - mv report.html $FOLDER

artifacts:
  files:
    - '**/*.html'
    - '**/*.png'
  name: log-report
